version: '2'

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.
    environment:
      NGINX_PORT: 80
    ports:
      - "80:80"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.
    environment:
      ASPNETCORE_URLS: http://*:2000
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./web:/app
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.
    environment:
      ASPNETCORE_URLS: http://*:2001
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./api:/app
  identity:
    build:
      context: ./IdentityServer
      dockerfile: Dockerfile.
    environment:
      EXTERNAL_URL: http://docker
      ASPNETCORE_URLS: http://*:2010
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ./IdentityServer:/app
  
      
